# Generated by Django 2.2.7 on 2019-12-01 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('idAdres', models.AutoField(primary_key=True, serialize=False)),
                ('ulica', models.CharField(max_length=200)),
                ('nrdomu', models.IntegerField()),
                ('nrmieszkania', models.IntegerField()),
                ('kodpocztowy', models.CharField(max_length=6)),
                ('miasto', models.CharField(max_length=45)),
                ('poczta', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Kierowcy',
            fields=[
                ('idKierowcy', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=200)),
                ('dataZatrudnienia', models.DateField(auto_now=True)),
                ('dataBadanie', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Zlecenie',
            fields=[
                ('idPaczka', models.AutoField(primary_key=True, serialize=False)),
                ('stanZlecenie', models.CharField(max_length=150)),
                ('typPaczka', models.CharField(max_length=150)),
                ('komentarz', models.TextField(max_length=500)),
                ('idAdresNadawca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_odbiorca', to='trackparc.Adres')),
                ('idAdresOdbiorca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_nadawca', to='trackparc.Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Przydzial',
            fields=[
                ('idPrzydzial', models.AutoField(primary_key=True, serialize=False)),
                ('idKierowcy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackparc.Kierowcy')),
                ('idPaczka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackparc.Zlecenie')),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('idKlient', models.AutoField(primary_key=True, serialize=False)),
                ('idAdres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackparc.Adres')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DaneKlient',
            fields=[
                ('idDane', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('nazwa', models.CharField(max_length=200)),
                ('nip', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=200)),
                ('idKlient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackparc.Klient')),
            ],
        ),
    ]
