# Generated by Django 2.2.7 on 2020-01-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackparc', '0002_daneklient_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daneklient',
            name='idKlient',
        ),
        migrations.RemoveField(
            model_name='daneklient',
            name='login',
        ),
        migrations.DeleteModel(
            name='Klient',
        ),
    ]
